### ISSUE TITLE
Release Process! (ROLLING LIVE ON JAMMY) :green_circle: :honey_pot: 

### ISSUE THREAD

**Issue by methylDragon** [ros-acceleration/ament_acceleration#1]
## Buildfarm Status
- [![Build Status](https://build.ros2.org/job/Rdev__ament_acceleration__ubuntu_jammy_amd64/badge/icon)](https://build.ros2.org/job/Rdev__ament_acceleration__ubuntu_jammy_amd64/) **dev** (ubuntu_jammy_amd64)
- [![Build Status](https://build.ros2.org/job/Rdoc__ament_acceleration__ubuntu_jammy_amd64/badge/icon)](https://build.ros2.org/job/Rdoc__ament_acceleration__ubuntu_jammy_amd64/) **doc** (ubuntu_jammy_amd64)
- [![Build Status](https://build.ros2.org/job/Rsrc_el8__ament_acceleration__rhel_8__source/badge/icon)](https://build.ros2.org/job/Rsrc_el8__ament_acceleration__rhel_8__source/) **src** (rhel_8)
- [![Build Status](https://build.ros2.org/job/Rsrc_uJ__ament_acceleration__ubuntu_jammy__source/badge/icon)](https://build.ros2.org/job/Rsrc_uJ__ament_acceleration__ubuntu_jammy__source/) **src** (ubuntu_jammy)
- [![Build Status](https://build.ros2.org/job/Rbin_uJ64__ament_acceleration__ubuntu_jammy_amd64__binary/badge/icon)](https://build.ros2.org/job/Rbin_uJ64__ament_acceleration__ubuntu_jammy_amd64__binary/) **bin** (ubuntu_jammy_amd64)
- [![Build Status](https://build.ros2.org/job/Rbin_rhel_el864__ament_acceleration__rhel_8_x86_64__binary/badge/icon)](https://build.ros2.org/job/Rbin_rhel_el864__ament_acceleration__rhel_8_x86_64__binary/) **bin** (rhel_8_x86_64)
- [![Build Status](https://build.ros2.org/job/Rbin_ujv8_uJv8__ament_acceleration__ubuntu_jammy_arm64__binary/badge/icon)](https://build.ros2.org/job/Rbin_ujv8_uJv8__ament_acceleration__ubuntu_jammy_arm64__binary/) **bin** (ubuntu_jammy_arm64)

## Description
This issue tracks the status for the release of this repository into `rosdistro` and making it available for installation as `.deb` via the ROS 2 repositories.

It will detail the steps that need to be taken, and what recommended changes are good to have.

### Personal Note
I think this is ready for release, we just need to go through the release process. No changes required in the source that stand out to me.

### Steps
- [x] Create a **release tag** corresponding to the version specified in `package.xml` @vmayoral 
- [x] Create release repo (pending https://github.com/ros2-gbp/ros2-gbp-github-org/pull/22)
- [x] Do [`bloom` release](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)
  - [x] `bloom` should PR `rosdistro`, if not, **manually create a PR**
- [x] `rosdistro` team to review package and merge PR (1-2 days, 1 month to get apt installable)
  - https://github.com/ros/rosdistro/pull/32546
- [ ] Monitor build and release status on [repo page](http://repo.ros2.org/status_page/) and [buildfarm](https://build.ros2.org/)

### Recommendations
I am unsure if this package might get approved in such a barebones state, but it technically fits the requirements for release. You might want to be ready to explain the intended usage in the eventual release PR.

- You might want to consider having separate branches for each ros distro this package is targeting (where the release branch is `main`, and the devel branches are named after the ros distros). That way your development code and release code can be properly segmented.
- You can [enable PR testing](http://wiki.ros.org/buildfarm/Pull%20request%20testing), making it so that whenever PRs are made, it gets tested on the buildfarm!

**Comment by vmayoral** [comment]
>  - [ ] Create a release tag corresponding to the version specified in package.xml @vmayoral

- https://github.com/ros-acceleration/ament_acceleration/commit/f1568b1a0edc8055c04ca230c523d7f01b653cdc
- https://github.com/ros-acceleration/ament_acceleration/releases/tag/0.2.0

**Comment by methylDragon** [comment]
:+1:

**Comment by methylDragon** [comment]
Bloom release created!

Release repo: https://github.com/ros2-gbp/ament_acceleration-release
rosdistro PR here: https://github.com/ros/rosdistro/pull/32546

Small additional comments: I updated the recommendations section (it's about having multiple branches so that development and releases can be put into different branches.)

**Comment by vmayoral** [comment]
> You might want to consider having separate branches for each ros distro this package is targeting (where the release branch is main, and the devel branches are named after the ros distros). That way your development code and release code can be properly segmented.

That makes absolute sense. Created `humble` and `rolling` branches.

> You can [enable PR testing](http://wiki.ros.org/buildfarm/Pull%20request%20testing), making it so that whenever PRs are made, it gets tested on the buildfarm!

![imagen](https://user-images.githubusercontent.com/1375246/160627502-3aaa4132-f1ac-4977-a70b-5d26759638b4.png)

**Comment by methylDragon** [comment]
We have released! :tada: Now I can do the release for `ament_vitis`
https://github.com/ros/rosdistro/pull/32546

Be sure to:
- Check the status on http://repo.ros2.org/status_page/ and https://build.ros2.org/

Bonuses:
- The ROS 2 team has suggested to change the default branch of https://github.com/ros2-gbp/ament_acceleration-release to `master`. I don't seem to have the permissions to, could you check if you do? If you don't I'll have to go ping someone
- Before the branches were separated, the release was made. In a future release of this package, we need to remember to target the `rolling` and `humble` branches instead to `rosdistro`. I'll track that in a separate issue.

**Comment by methylDragon** [comment]
Speaking of which, @vmayoral do you think you could get `rolling` and `humble` branches on the other repos?

[`ament_vitis` ](https://github.com/ros-acceleration/ament_vitis) most importantly first, because I can already start the release process for that now that this package has been released, so it'll be good to get in so we won't need to retarget the branches again.

**Comment by vmayoral** [comment]
> The ROS 2 team has suggested to change the default branch of https://github.com/ros2-gbp/ament_acceleration-release to master. I don't seem to have the permissions to, could you check if you do? If you don't I'll have to go ping someone

Checked and can't neither. We need permissions. Can you ping whoever's empowered to grant them please?

**Comment by vmayoral** [comment]
Tried enabling test PRs https://github.com/ros/rosdistro/pull/32593

**Comment by vmayoral** [comment]
> Speaking of which, @vmayoral do you think you could get rolling and humble branches on the other repos?

I think we're good now.

**Comment by vmayoral** [comment]
I can see http://repo.ros2.org/status_page/ros_rolling_default.html?q=ament_acceleration in green, can you confirm we're good in here @methylDragon?

**Comment by methylDragon** [comment]
I think we're mostly good, I think I saw one failing build configuration on the buildfarm (I'm not sure if it's an issue from the package or the buildfarm), but I can't load the page today for some reason. :scream:

**Comment by methylDragon** [comment]
Found it!

[![Build Status](https://build.ros2.org/job/Rdev__ament_acceleration__ubuntu_jammy_amd64/badge/icon)](https://build.ros2.org/job/Rdev__ament_acceleration__ubuntu_jammy_amd64/)

This one is failing, I'm not sure why.. You can check the console.

**Comment by methylDragon** [comment]
(Also, because it's nice to see some green...)

The rest of the builds on Jenkins are fine (aside from the doc build)

[![Build Status](https://build.ros2.org/job/Rdoc__ament_acceleration__ubuntu_jammy_amd64/badge/icon)](https://build.ros2.org/job/Rdoc__ament_acceleration__ubuntu_jammy_amd64/)
[![Build Status](https://build.ros2.org/job/Rsrc_el8__ament_acceleration__rhel_8__source/badge/icon)](https://build.ros2.org/job/Rsrc_el8__ament_acceleration__rhel_8__source/)
[![Build Status](https://build.ros2.org/job/Rsrc_uJ__ament_acceleration__ubuntu_jammy__source/badge/icon)](https://build.ros2.org/job/Rsrc_uJ__ament_acceleration__ubuntu_jammy__source/)
[![Build Status](https://build.ros2.org/job/Rbin_uJ64__ament_acceleration__ubuntu_jammy_amd64__binary/badge/icon)](https://build.ros2.org/job/Rbin_uJ64__ament_acceleration__ubuntu_jammy_amd64__binary/)
[![Build Status](https://build.ros2.org/job/Rbin_rhel_el864__ament_acceleration__rhel_8_x86_64__binary/badge/icon)](https://build.ros2.org/job/Rbin_rhel_el864__ament_acceleration__rhel_8_x86_64__binary/)
[![Build Status](https://build.ros2.org/job/Rbin_ujv8_uJv8__ament_acceleration__ubuntu_jammy_arm64__binary/badge/icon)](https://build.ros2.org/job/Rbin_ujv8_uJv8__ament_acceleration__ubuntu_jammy_arm64__binary/)

**Comment by methylDragon** [comment]
- [![Build Status](https://build.ros2.org/job/Rdev__ament_acceleration__ubuntu_jammy_amd64/badge/icon)](https://build.ros2.org/job/Rdev__ament_acceleration__ubuntu_jammy_amd64/) **dev** (ubuntu_jammy_amd64)
- [![Build Status](https://build.ros2.org/job/Rdoc__ament_acceleration__ubuntu_jammy_amd64/badge/icon)](https://build.ros2.org/job/Rdoc__ament_acceleration__ubuntu_jammy_amd64/) **doc** (ubuntu_jammy_amd64)
- [![Build Status](https://build.ros2.org/job/Rsrc_el8__ament_acceleration__rhel_8__source/badge/icon)](https://build.ros2.org/job/Rsrc_el8__ament_acceleration__rhel_8__source/) **src** (rhel_8)
- [![Build Status](https://build.ros2.org/job/Rsrc_uJ__ament_acceleration__ubuntu_jammy__source/badge/icon)](https://build.ros2.org/job/Rsrc_uJ__ament_acceleration__ubuntu_jammy__source/) **src** (ubuntu_jammy)
- [![Build Status](https://build.ros2.org/job/Rbin_uJ64__ament_acceleration__ubuntu_jammy_amd64__binary/badge/icon)](https://build.ros2.org/job/Rbin_uJ64__ament_acceleration__ubuntu_jammy_amd64__binary/) **bin** (ubuntu_jammy_amd64)
- [![Build Status](https://build.ros2.org/job/Rbin_rhel_el864__ament_acceleration__rhel_8_x86_64__binary/badge/icon)](https://build.ros2.org/job/Rbin_rhel_el864__ament_acceleration__rhel_8_x86_64__binary/) **bin** (rhel_8_x86_64)
- [![Build Status](https://build.ros2.org/job/Rbin_ujv8_uJv8__ament_acceleration__ubuntu_jammy_arm64__binary/badge/icon)](https://build.ros2.org/job/Rbin_ujv8_uJv8__ament_acceleration__ubuntu_jammy_arm64__binary/) **bin** (ubuntu_jammy_arm64)

**Comment by methylDragon** [comment]
Dev build is failing because of https://github.com/ros-infrastructure/ros_buildfarm/pull/950

I think there's going to be a PR soon to handle this case, so we'll wait out for it.

EDIT: PR pending: https://github.com/ros-infrastructure/ros_buildfarm/pull/955

**Comment by methylDragon** [comment]
@osrf-jenkins run tests

**Comment by methylDragon** [comment]
@vmayoral I forced a rebuild, green now! :tada:

**Comment by vmayoral** [comment]
> @vmayoral I forced a rebuild, green now! 🎉

Thanks, to confirm, is this something that you guys do internally or is there a specific syntax to do so? E.g. I saw you posted previously:

> [@osrf-jenkins](https://github.com/osrf-jenkins) run tests

**Comment by methylDragon** [comment]
That doesn't work haha, I was just trying something (and it didn't work. )`: )

Rebuilds have to be triggered manually on the internal buildfarm (with the appropriate permissions.) But they also trigger on changes or PRs.

**Comment by methylDragon** [comment]
Closing this issue, since we're done :tada: 
Congratulations on the press release too!
