### ISSUE TITLE
Target Different Release Branch

### ISSUE THREAD

**Issue by methylDragon** [ros-acceleration/ament_acceleration#2]
On `rosdistro`, this package is targeting the `main` branch for the `rolling` distribution.

https://github.com/ros/rosdistro/blob/cca10b4cece1f8c4083a40dcea02da674011f440/rolling/distribution.yaml#L57

It would be good to adjust it to the `rolling` branch instead. Perhaps best done during the `humble` release.

**Comment by methylDragon** [comment]
I've released a PR for this anyway on `rosdistro` https://github.com/ros/rosdistro/pull/32587

**Comment by vmayoral** [comment]
Thanks for this, I can see it's been merged. Closing in here.
